### ISSUE TITLE
prop.table values not matching heat map

### ISSUE THREAD

**Issue by kariljordan** [carpentries/assessment#124]
On https://carpentries.github.io/assessment/carpentries/long-term-survey/report.html I provide a bulleted list of highlights from the data. I use (as an example)

```
Confidence_Change <- round(prop.table(table(data$`Change-In-Confidence`)) * 100)
```

and 

```
+ `r Confidence_Change[3]`% of respondents reported being more confident in the tools that 
were covered during their workshop compared to before the workshop.
```
to pull the data into the report. I noticed that the percentages in some of the prop.tables do not correspond to the percentages in the heatmap. For the heatmap I use:

```
title <- "Perception of Workshop Impact"		
plot(data_agree_likert, type =c("heat"), panel.arrange = NULL, panel.strip.color = "red", legend.position = "bottom") + ggtitle(title)
ggsave("figures/workshop_impact_heatmap.png")
```
and it looks like [this](https://github.com/carpentries/assessment/blob/master/carpentries/long-term-survey/figures/workshop_impact_heatmap.png?raw=true).

I'd appreciate some insight as I would like to get a DOI for this report and want it to be correct before doing so.

**Comment by benmarwick** [comment]
I think there are actually two separate 'confidence' variables here! 

Firstly, we have the column in `data` that is `Change-In-Confidence`, the first one that you mention. This corresponds to the survey question "12. How would you rate your change in confidence in the tools that were covered during your Carpentry workshop(s) compared to before the workshop?"

Secondly, we have another column in `data` that is `Gained-Confidence-With-Data`, and that is what makes the percentages in the heatmap. This column comes from the survey question "17. The statements below reflect ways in which completing a Carpentry workshop may have impacted
you. Please indicate your level of agreement with these statements." and the specific row "I have gained
confidence in working with data as a result of completing the workshop."

Because they are different variables, we shouldn't expect the percentages to be the same. So we should say the first one is about **confidence in tools** and the second one is about **confidence in working with data**. Does that make sense?

**Comment by kariljordan** [comment]
@benmarwick That makes PERFECT SENSE-and I have no idea how I missed that! Ok I'm going to change the wording now! Thank you!
