### ISSUE TITLE
Update programmatic assessment readme to include instructor training

### ISSUE THREAD

**Issue by maneesha** [carpentries/assessment#208]
The [readme](https://github.com/carpentries/assessment/blob/master/programmatic-assessment/readme.md) file in the programmatic assessment folder of this repo refers only to what's in the `workshops` folder.  There is also an `instructor_training` folder that has its own readme (without much information in it).  

Should there be one readme in the programmatic assessment folder or should the existing readme be moved to the `workshops` folder (leaving no readme directly under programmatic assessment)?

Pinging @ErinBecker  @karenword  @kariljordan  for feedback

**Comment by ErinBecker** [comment]
I think there should be only a single README for the programmatic assessment folder. The instructor training folder is very outdated right now (over a year old with no updates). If you (@maneesha) decide to update the analysis of instructor training applications in one of the new programmatic reports, that would be great. Otherwise, I move that we mark that folder as defunct until there is an update.

**Comment by maneesha** [comment]
We can mark this as defunct until it's addressed in one of the upcoming programmatic assessment reports.
I'll take care of that this week.

**Comment by maneesha** [comment]
fixed with 67eaa78512f728c8fb9e4163
